/**
 * People automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("A People is an individual person or character within the Star Wars universe")
public class People {
    @JsonPropertyDescription("The name of this person.")
    private String name;
    @JsonPropertyDescription("The birth year of the person, using the in-universe standard of BBY or ABY - Before the Battle of Yavin or After the Battle of Yavin. The Battle of Yavin is a battle that occurs at the end of Star Wars episode IV: A New Hope.")
    private String birthYear;
    @JsonPropertyDescription("The eye color of this person. Will be "unknown" if not known or "n/a" if the person does not have an eye.")
    private String eyeColor;
    @JsonPropertyDescription("The gender of this person. Either "Male", "Female" or "unknown", "n/a" if the person does not have a gender.")
    private String gender;
    @JsonPropertyDescription("The hair color of this person. Will be "unknown" if not known or "n/a" if the person does not have hair.")
    private String hairColor;
    @JsonPropertyDescription("The height of the person in centimeters.")
    private String height;
    @JsonPropertyDescription("The mass of the person in kilograms.")
    private String mass;
    @JsonPropertyDescription("The skin color of this person.")
    private String skinColor;
    @JsonPropertyDescription("The URL of a planet resource, a planet that this person was born on or inhabits.")
    private String homeworld;
    @JsonPropertyDescription("An array of film resource URLs that this person has been in.")
    private java.util.List<String> films;
    @JsonPropertyDescription("An array of species resource URLs that this person belongs to.")
    private java.util.List<String> species;
    @JsonPropertyDescription("An array of starship resource URLs that this person has piloted.")
    private java.util.List<String> starships;
    @JsonPropertyDescription("An array of vehicle resource URLs that this person has piloted.")
    private java.util.List<String> vehicles;
    @JsonPropertyDescription("The hypermedia URL of this resource.")
    private String url;
    @JsonPropertyDescription("The ISO 8601 date format of the time that this resource was created.")
    private java.time.LocalDateTime created;
    @JsonPropertyDescription("The ISO 8601 date format of the time that this resource was edited. Search Fields:")
    private java.time.LocalDateTime edited;

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("birth_year")
    public void setBirthYear(String birthYear) {
        this.birthYear = birthYear;
    }

    @JsonGetter("birth_year")
    public String getBirthYear() {
        return this.birthYear;
    }

    @JsonSetter("eye_color")
    public void setEyeColor(String eyeColor) {
        this.eyeColor = eyeColor;
    }

    @JsonGetter("eye_color")
    public String getEyeColor() {
        return this.eyeColor;
    }

    @JsonSetter("gender")
    public void setGender(String gender) {
        this.gender = gender;
    }

    @JsonGetter("gender")
    public String getGender() {
        return this.gender;
    }

    @JsonSetter("hair_color")
    public void setHairColor(String hairColor) {
        this.hairColor = hairColor;
    }

    @JsonGetter("hair_color")
    public String getHairColor() {
        return this.hairColor;
    }

    @JsonSetter("height")
    public void setHeight(String height) {
        this.height = height;
    }

    @JsonGetter("height")
    public String getHeight() {
        return this.height;
    }

    @JsonSetter("mass")
    public void setMass(String mass) {
        this.mass = mass;
    }

    @JsonGetter("mass")
    public String getMass() {
        return this.mass;
    }

    @JsonSetter("skin_color")
    public void setSkinColor(String skinColor) {
        this.skinColor = skinColor;
    }

    @JsonGetter("skin_color")
    public String getSkinColor() {
        return this.skinColor;
    }

    @JsonSetter("homeworld")
    public void setHomeworld(String homeworld) {
        this.homeworld = homeworld;
    }

    @JsonGetter("homeworld")
    public String getHomeworld() {
        return this.homeworld;
    }

    @JsonSetter("films")
    public void setFilms(java.util.List<String> films) {
        this.films = films;
    }

    @JsonGetter("films")
    public java.util.List<String> getFilms() {
        return this.films;
    }

    @JsonSetter("species")
    public void setSpecies(java.util.List<String> species) {
        this.species = species;
    }

    @JsonGetter("species")
    public java.util.List<String> getSpecies() {
        return this.species;
    }

    @JsonSetter("starships")
    public void setStarships(java.util.List<String> starships) {
        this.starships = starships;
    }

    @JsonGetter("starships")
    public java.util.List<String> getStarships() {
        return this.starships;
    }

    @JsonSetter("vehicles")
    public void setVehicles(java.util.List<String> vehicles) {
        this.vehicles = vehicles;
    }

    @JsonGetter("vehicles")
    public java.util.List<String> getVehicles() {
        return this.vehicles;
    }

    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    @JsonGetter("url")
    public String getUrl() {
        return this.url;
    }

    @JsonSetter("created")
    public void setCreated(java.time.LocalDateTime created) {
        this.created = created;
    }

    @JsonGetter("created")
    public java.time.LocalDateTime getCreated() {
        return this.created;
    }

    @JsonSetter("edited")
    public void setEdited(java.time.LocalDateTime edited) {
        this.edited = edited;
    }

    @JsonGetter("edited")
    public java.time.LocalDateTime getEdited() {
        return this.edited;
    }
}

