/**
 * PeopleCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class PeopleCollection extends Collection {
    private List<People> results;
    @JsonSetter("results")
    public void setResults(List<People> results) {
        this.results = results;
    }
    @JsonGetter("results")
    public List<People> getResults() {
        return this.results;
    }
}
