/**
 * Root automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.*;

public class Root {
    private String films;
    private String people;
    private String planets;
    private String species;
    private String starships;
    private String vehicles;

    @JsonSetter("films")
    public void setFilms(String films) {
        this.films = films;
    }

    @JsonGetter("films")
    public String getFilms() {
        return this.films;
    }

    @JsonSetter("people")
    public void setPeople(String people) {
        this.people = people;
    }

    @JsonGetter("people")
    public String getPeople() {
        return this.people;
    }

    @JsonSetter("planets")
    public void setPlanets(String planets) {
        this.planets = planets;
    }

    @JsonGetter("planets")
    public String getPlanets() {
        return this.planets;
    }

    @JsonSetter("species")
    public void setSpecies(String species) {
        this.species = species;
    }

    @JsonGetter("species")
    public String getSpecies() {
        return this.species;
    }

    @JsonSetter("starships")
    public void setStarships(String starships) {
        this.starships = starships;
    }

    @JsonGetter("starships")
    public String getStarships() {
        return this.starships;
    }

    @JsonSetter("vehicles")
    public void setVehicles(String vehicles) {
        this.vehicles = vehicles;
    }

    @JsonGetter("vehicles")
    public String getVehicles() {
        return this.vehicles;
    }
}

