/**
 * SpecieCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class SpecieCollection extends Collection {
    private List<Specie> results;
    @JsonSetter("results")
    public void setResults(List<Specie> results) {
        this.results = results;
    }
    @JsonGetter("results")
    public List<Specie> getResults() {
        return this.results;
    }
}
