/**
 * SpeciesCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class SpeciesCollection extends Collection {
    private List<Species> results;
    @JsonSetter("results")
    public void setResults(List<Species> results) {
        this.results = results;
    }
    @JsonGetter("results")
    public List<Species> getResults() {
        return this.results;
    }
}
