/**
 * StarshipCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class StarshipCollection extends Collection {
    private java.util.List<Starship> results;
    @JsonSetter("results")
    public void setResults(java.util.List<Starship> results) {
        this.results = results;
    }
    @JsonGetter("results")
    public java.util.List<Starship> getResults() {
        return this.results;
    }
}
