/**
 * VehicleCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.*;

public class VehicleCollection extends Collection {
    private java.util.List<Vehicle> results;

    @JsonSetter("results")
    public void setResults(java.util.List<Vehicle> results) {
        this.results = results;
    }

    @JsonGetter("results")
    public java.util.List<Vehicle> getResults() {
        return this.results;
    }
}

