/**
 * VehicleCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.starwars;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class VehicleCollection extends Collection {
    private List<Vehicle> results;
    @JsonSetter("results")
    public void setResults(List<Vehicle> results) {
        this.results = results;
    }
    @JsonGetter("results")
    public List<Vehicle> getResults() {
        return this.results;
    }
}
